spring:
  application:
    name: vs-image-search-mcp-server
  ai:
    mcp:
      server:
        name: vs-image-search-mcp-server
        version: 0.0.1
        type: SYNC
        # sse
        stdio: false
server:
  port: 8123